version: "3.9"
   
services:
  postgres:
    image: postgres:12-alpine
    ports:
        - "${DB_PORT}:5432"
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PGGSSENCMODE=disable
    volumes:
        - "./dbdata:/var/lib/postgresql/data"
  django:
    build: 
      context: .
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
